<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.14.1 setup script
 * Date: Wed, 28 Oct 2015 11:55:59 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: we-mysql [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'we-mysql';
$cfg['Servers'][$i]['host'] = 'we-mysql';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = '123456';
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['controlhost'] = 'we-mysql';
$cfg['Servers'][$i]['controluser'] = 'admin';
$cfg['Servers'][$i]['controlpass'] = '123456';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>